# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81841c7028d30626a9c46cc1e037b64a467012c5f8d4c4abc4ecb10509615469b67b050bdeccd315fdc82fbad9b22258aab2c6946cfed1cdd742c616391bc0b8

test:
  secret_key_base: 7eab484f22483b76fdc0df2c38cabb8074901134faf46d851e3604dbf3050ba1805d48da7b93432a7eb82962071d10365fdbbfa4172291478d34a6f59616381e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
